#!/bin/sh
#
# Usage: gputest.sh
# Change job name and email address as needed 
#        
# -- our name ---
#$ -N GANs
#$ -S /bin/sh
# Make sure that the .e and .o file arrive in the
#working directory
#$ -cwd
#Merge the standard out and standard error to one file
#$ -j y
# Send mail at submission and completion of script
#$ -m be

# Request a gpu
#$ -q datasci
### #$ -q short

/bin/echo Running on host: `hostname`.
/bin/echo In directory: `pwd`
/bin/echo Starting on: `date`
 
# Load CUDA module
. /opt/modules/init/bash
module load cuda
module load python3.6
#module load gsl-gnu4
#export LD_LIBRARY_PATH=/opt/gsl/1.15/gnu4/lib:$LD_LIBRARY_PATH

#python flower_image_classification_mc.py
#python flower_classification_cnn.py
#python train90model3.py sub_imagenet/train model.h5 > output1
#python test.py sub_imagenet/val model.h5 > output
#KERAS_BACKEND=tensorflow python cifar10_cnn_v3.py

#python train1.py x_train.npy y_train.npy model2.h5


python train.py directory model.h5 > output
python test.py model.h5 outputFile
